export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Nav } from './Nav'
export { default as Projects } from './Projects'
export { default as Technologies } from './Technologies'
export { default as Layout } from './_layout'
export * from './index'
